 2-17-25
 This analysis focuses on different jobs in the healthcare, compares nationally and by state
 Data is from National Bureau of Labor Statistics, is from May 2024
 https://data.bls.gov/oes/#/area/0600000

# First point of interest: CNA positions in WV vs CA vs Nationally

# Reference codes
To find occupations, use OCC code or SOC code. for CNAS it is 31-1131

Compare the rate / percent of cnas in WV to CA to Nationally.  use per 1k people 
for nationally, i get per 1k people by doing: cna number/jobs number x 1000
and to make it a percent jsut multipyl that result by 100

25% more CNAS in wv then nationally: cna/1000 x 100
national cna avg / 1000 x 100 
first number - second = 0.25

# Col names guide: 
see the column_names_descriptions file in this folder

In [42]:
#Imports
import plotly.express as px
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
#Loading csvs into postegree sql
# df_by_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/by_state_job_stats_bls.csv")
# engine= create_engine('postgresql+psycopg2://postgres:Jehovah1@localhost:5432/bls_jobs')
# df_by_job_stats.columns=[col.lower() for col in df_by_job_stats]
# df_by_job_stats.to_sql('by_state_job_stats', engine, if_exists='replace', index=False)

#national one
# df_national_jobs_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/national_job_stats_bls.csv")
# engine= create_engine('postgresql+psycopg2://postgres:Jehovah1@localhost:5432/bls_jobs')
# df_national_jobs_stats.columns=[col.lower() for col in df_national_jobs_stats]
# df_national_jobs_stats.to_sql('national_job_stats', engine, if_exists='replace', index=False)

# EDA

In [44]:
df_cna_by_state_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/CNA_by_state_job_stats_bls.csv")
df_cna_national_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/CNA_national_job_stats_bls.csv")

In [45]:
df_cna_by_state_job_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area          54 non-null     int64
 1   area_title    54 non-null     object
 2   area_type     54 non-null     int64
 3   prim_state    54 non-null     object
 4   naics         54 non-null     int64
 5   naics_title   54 non-null     object
 6   i_group       54 non-null     object
 7   own_code      54 non-null     int64
 8   occ_code      54 non-null     object
 9   occ_title     54 non-null     object
 10  o_group       54 non-null     object
 11  tot_emp       54 non-null     object
 12  emp_prse      54 non-null     float64
 13  jobs_1000     54 non-null     float64
 14  loc_quotient  54 non-null     float64
 15  pct_total     0 non-null      float64
 16  pct_rpt       0 non-null      float64
 17  h_mean        54 non-null     float64
 18  a_mean        54 non-null     object
 19  mean_prse     54 non-null     float64
 20  h_pct10       54 non-null     float64
 21  h_pct25       54 non-null     float64
 22  h_median      54 non-null     float64
 23  h_pct75       54 non-null     float64
 24  h_pct90       54 non-null     float64
 25  a_pct10       54 non-null     object
 26  a_pct25       54 non-null     object
 27  a_median      54 non-null     object
 28  a_pct75       54 non-null     object
 29  a_pct90       54 non-null     object
 30  annual        0 non-null      float64
 31  hourly        0 non-null      float64
 32  id            54 non-null     int64
dtypes: float64(14), int64(5), object(14)
memory usage: 14.1+ KB

In [46]:
#Changing a_mean to a int type so i can get avg and stuff
df_cna_by_state_job_stats['a_mean'] = pd.to_numeric(df_cna_by_state_job_stats['a_mean'].str.replace(',', ''), errors='coerce')
df_cna_by_state_job_stats['a_mean']

0     32670
1     48550
2     43060
3     33350
4     48790
5     45480
6     44860
7     40120
8     47480
9     38320
10    37090
11    45480
12    37740
13    43950
14    38610
15    40590
16    38600
17    37960
18    31700
19    45500
20    42070
21    46130
22    40210
23    45230
24    31750
25    37650
26    42020
27    40830
28    44360
29    47190
30    44480
31    38320
32    47530
33    37980
34    42530
35    39840
36    34900
37    49970
38    41700
39    43740
40    35970
41    38070
42    37040
43    37010
44    39240
45    43610
46    40160
47    49960
48    36320
49    43050
50    41040
51    34750
52    25060
53    40970
Name: a_mean, dtype: int64

In [47]:
#check that mean type is now numeric 
df_cna_by_state_job_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area          54 non-null     int64
 1   area_title    54 non-null     object
 2   area_type     54 non-null     int64
 3   prim_state    54 non-null     object
 4   naics         54 non-null     int64
 5   naics_title   54 non-null     object
 6   i_group       54 non-null     object
 7   own_code      54 non-null     int64
 8   occ_code      54 non-null     object
 9   occ_title     54 non-null     object
 10  o_group       54 non-null     object
 11  tot_emp       54 non-null     object
 12  emp_prse      54 non-null     float64
 13  jobs_1000     54 non-null     float64
 14  loc_quotient  54 non-null     float64
 15  pct_total     0 non-null      float64
 16  pct_rpt       0 non-null      float64
 17  h_mean        54 non-null     float64
 18  a_mean        54 non-null     int64
 19  mean_prse     54 non-null     float64
 20  h_pct10       54 non-null     float64
 21  h_pct25       54 non-null     float64
 22  h_median      54 non-null     float64
 23  h_pct75       54 non-null     float64
 24  h_pct90       54 non-null     float64
 25  a_pct10       54 non-null     object
 26  a_pct25       54 non-null     object
 27  a_median      54 non-null     object
 28  a_pct75       54 non-null     object
 29  a_pct90       54 non-null     object
 30  annual        0 non-null      float64
 31  hourly        0 non-null      float64
 32  id            54 non-null     int64
dtypes: float64(14), int64(6), object(13)
memory usage: 14.1+ KB

In [48]:
#doing the same for total employees so i can do calculations with them 
df_cna_by_state_job_stats['tot_emp'] = pd.to_numeric(df_cna_by_state_job_stats['tot_emp'].str.replace(',', ''), errors='coerce')
df_cna_by_state_job_stats['tot_emp']

0      24560
1       1660
2      17350
3      17620
4     102380
5      20880
6      21390
7       5660
8       2550
9      91280
10     42460
11      4620
12      7340
13     64660
14     31240
15     22970
16     23950
17     22910
18     20550
19      8590
20     24230
21     38280
22     40230
23     26970
24     13130
25     32650
26      4800
27     16490
28      8670
29      7190
30     31310
31      4600
32     85310
33     61280
34      6920
35     62360
36     19860
37     12800
38     65410
39      8450
40     21000
41      6520
42     23030
43     87050
44     12350
45      3140
46     42760
47     28080
48      8860
49     27480
50      2680
51       240
52       770
53       120
Name: tot_emp, dtype: int64

In [49]:
#check that total employee data type is now a numeric 
df_cna_by_state_job_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area          54 non-null     int64
 1   area_title    54 non-null     object
 2   area_type     54 non-null     int64
 3   prim_state    54 non-null     object
 4   naics         54 non-null     int64
 5   naics_title   54 non-null     object
 6   i_group       54 non-null     object
 7   own_code      54 non-null     int64
 8   occ_code      54 non-null     object
 9   occ_title     54 non-null     object
 10  o_group       54 non-null     object
 11  tot_emp       54 non-null     int64
 12  emp_prse      54 non-null     float64
 13  jobs_1000     54 non-null     float64
 14  loc_quotient  54 non-null     float64
 15  pct_total     0 non-null      float64
 16  pct_rpt       0 non-null      float64
 17  h_mean        54 non-null     float64
 18  a_mean        54 non-null     int64
 19  mean_prse     54 non-null     float64
 20  h_pct10       54 non-null     float64
 21  h_pct25       54 non-null     float64
 22  h_median      54 non-null     float64
 23  h_pct75       54 non-null     float64
 24  h_pct90       54 non-null     float64
 25  a_pct10       54 non-null     object
 26  a_pct25       54 non-null     object
 27  a_median      54 non-null     object
 28  a_pct75       54 non-null     object
 29  a_pct90       54 non-null     object
 30  annual        0 non-null      float64
 31  hourly        0 non-null      float64
 32  id            54 non-null     int64
dtypes: float64(14), int64(7), object(12)
memory usage: 14.1+ KB

In [50]:
#total num of nulls 
print(df_cna_by_state_job_stats.isna().sum().sum())

216

In [51]:
#4 columns have only null vlaues so ill drop them 
df_cna_by_state_job_stats.drop(['pct_total','pct_rpt','hourly', 'annual'], axis=1, inplace=True)
df_cna_by_state_job_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 29 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area          54 non-null     int64
 1   area_title    54 non-null     object
 2   area_type     54 non-null     int64
 3   prim_state    54 non-null     object
 4   naics         54 non-null     int64
 5   naics_title   54 non-null     object
 6   i_group       54 non-null     object
 7   own_code      54 non-null     int64
 8   occ_code      54 non-null     object
 9   occ_title     54 non-null     object
 10  o_group       54 non-null     object
 11  tot_emp       54 non-null     int64
 12  emp_prse      54 non-null     float64
 13  jobs_1000     54 non-null     float64
 14  loc_quotient  54 non-null     float64
 15  h_mean        54 non-null     float64
 16  a_mean        54 non-null     int64
 17  mean_prse     54 non-null     float64
 18  h_pct10       54 non-null     float64
 19  h_pct25       54 non-null     float64
 20  h_median      54 non-null     float64
 21  h_pct75       54 non-null     float64
 22  h_pct90       54 non-null     float64
 23  a_pct10       54 non-null     object
 24  a_pct25       54 non-null     object
 25  a_median      54 non-null     object
 26  a_pct75       54 non-null     object
 27  a_pct90       54 non-null     object
 28  id            54 non-null     int64
dtypes: float64(10), int64(7), object(12)
memory usage: 12.4+ KB

In [52]:
#re-check to make sure all nulls are gone 
print(df_cna_by_state_job_stats.isna().sum().sum())

0

In [53]:
df_cna_by_state_job_stats.describe() #summary stats

,area,area_type,naics,own_code,tot_emp,emp_prse,jobs_1000,loc_quotient,h_mean,a_mean,mean_prse,h_pct10,h_pct25,h_median,h_pct75,h_pct90,id
count,54.000000,54.000000,54.0,54.0,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000,54.000000
mean,31.351852,2.055556,0.0,1235.0,25734.074074,4.009259,9.663333,1.072593,19.592778,40751.481481,1.157407,16.023519,17.520556,19.187778,21.199259,23.542407,19283.314815
std,18.354124,0.231212,0.0,0.0,25144.636438,3.397072,3.533060,0.392573,2.456926,5108.667960,1.641054,2.213340,2.185634,2.604052,2.714050,2.849051,11318.983766
min,1.000000,2.000000,0.0,1235.0,120.000000,1.600000,0.819000,0.090000,12.050000,25060.000000,0.300000,9.500000,9.570000,9.840000,10.660000,18.140000,338.000000
25%,17.250000,2.000000,0.0,1235.0,7227.500000,2.525000,7.257750,0.805000,18.167500,37795.000000,0.600000,14.267500,16.552500,17.762500,19.932500,22.025000,9555.750000
50%,30.500000,2.000000,0.0,1235.0,20715.000000,3.050000,9.521000,1.060000,19.570000,40710.000000,0.800000,16.540000,17.735000,18.675000,21.480000,23.130000,19356.000000
75%,44.750000,2.000000,0.0,1235.0,31292.500000,4.100000,11.675500,1.295000,21.367500,44450.000000,1.100000,17.885000,19.027500,21.542500,23.060000,25.387500,28943.750000
max,78.000000,3.000000,0.0,1235.0,102380.000000,24.500000,17.110000,1.900000,24.030000,49970.000000,12.200000,19.800000,21.750000,23.270000,26.930000,29.090000,37493.000000

In [54]:
# df_all_national_job_stats = df_cna_national_job_stats[df_cna_national_job_stats['occ_code'] == '00-0000']
# df_all_national_job_stats.head()

In [55]:
fig = px.box(df_cna_by_state_job_stats, y = ['jobs_1000','h_mean'])
fig.show()

#below figure shows that the median(not avg) rate of CNA jobs/1000 is 9/1000
#also shows median hourly wage is 19.57 

#while nationally for all jobs, hourly wage avg(not median) is 32

In [56]:
#states w more cnas then avg per 1k ppl(9.6)

In [57]:
df_states_with_highest_cnas = df_cna_by_state_job_stats[df_cna_by_state_job_stats['jobs_1000'] > 9.7]
df_states_with_highest_cnas.sort_values(by='jobs_1000',ascending=False, inplace=True)
# df_stats_with_highest_cnas

/var/folders/9r/0wy81gln1bv565v23phr081h0000gn/T/ipykernel_32544/208753449.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
#filtering above by top 10 highest CNA states
df_top_ten_sates_with_highest_cnas = df_states_with_highest_cnas.iloc[0:10]
df_top_ten_sates_with_highest_cnas

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90,id
39,44,Rhode Island,2,RI,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,18.79,21.23,22.50,24.01,"38,190","39,070","44,160","46,790","49,950",28460
16,20,Kansas,2,KS,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,16.96,17.75,19.98,22.11,"31,140","35,280","36,910","41,560","45,980",11639
34,38,North Dakota,2,ND,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,17.34,21.25,22.54,24.03,"34,620","36,060","44,190","46,880","49,970",24746
27,31,Nebraska,2,NE,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,17.83,18.57,21.47,23.06,"35,790","37,080","38,620","44,660","47,970",19686
15,19,Iowa,2,IA,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,17.66,18.57,21.49,23.13,"35,070","36,740","38,630","44,710","48,100",10912
41,46,South Dakota,2,SD,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,16.83,18.30,19.93,21.67,"29,960","35,010","38,070","41,440","45,070",29789
3,5,Arkansas,2,AR,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,14.26,15.38,17.36,18.96,"28,330","29,670","31,990","36,120","39,430",2368
19,23,Maine,2,ME,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,19.36,21.94,23.27,26.24,"37,350","40,270","45,640","48,390","54,580",13810
6,9,Connecticut,2,CT,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,19.12,21.40,23.13,24.90,"38,450","39,760","44,500","48,110","51,790",4689
48,54,West Virginia,2,WV,0,Cross-industry,cross-industry,1235,31-1131,Nursing Assistants,...,15.88,17.47,18.80,20.29,"29,850","33,020","36,340","39,090","42,210",34931

# CNA concentration

## bar of top ten

In [59]:
#avg of cna
fig_top_10_cna_concentration = px.bar(df_top_ten_sates_with_highest_cnas, y='jobs_1000', x='area_title', title="States with highest CNA concentration", color_discrete_sequence=['pink'])
fig_top_10_cna_concentration.show()

In [60]:
df_all_national_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/national_job_stats_bls.csv")
# cna = df_all_national_job_stats['OCC_CODE'] == '31-1131'
# cna = df_all['OCC_TITLE']== 'Nursing Assistant'
df_all_national_job_stats['TOT_EMP'] = pd.to_numeric(df_all_national_job_stats['TOT_EMP'].str.replace(',', ''), errors='coerce')
# CNA count
count_cna = df_all_national_job_stats.loc[df_all_national_job_stats['OCC_TITLE'] == 'Nursing Assistants', 'TOT_EMP'].sum()

total_jobs = df_all_national_job_stats.iloc[0]['TOT_EMP']

# Other jobs
count_other = total_jobs - count_cna

# Check percentage


count_other

np.int64(152798950)

In [61]:
labels = ['Nursing Assitants', 'Other']
values = [count_cna, count_other]
px.pie(names=labels, values=values)

In [62]:
wv = df_top_ten_sates_with_highest_cnas.iloc[9]

df_all_state_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/by_state_job_stats_bls.csv")
df_all_state_job_stats['TOT_EMP'] = pd.to_numeric(df_all_state_job_stats['TOT_EMP'].str.replace(',', ''), errors='coerce')
count_cna_wv = wv.loc['tot_emp'].sum()

print(count_cna_wv)
df_all_state_job_stats['AREA_TITLE']
# df_all_national_job_stats.loc[df_all_national_job_stats['OCC_TITLE'] == 'Nursing Assistants', 'TOT_EMP'].sum()

total_jobs_wv = df_all_state_job_stats.loc[(df_all_state_job_stats["OCC_CODE"] == '00-0000') & (df_all_state_job_stats["AREA_TITLE"] == 'West Virginia'), 'TOT_EMP'].iloc[0]
# total_jobs_wv = df_all_state_job_stats.loc[df_all_state_job_stats['AREA_TITLE'] == 'West Virginia', 'TOT_EMP'].sum()
print(total_jobs_wv)

# Other jobs
count_other_wv = total_jobs_wv - count_cna_wv
print(count_other_wv)

8860
701470.0
692610.0

In [63]:
labels = ['Nursing Assitants', 'Other']
values = [count_cna_wv, count_other_wv]
px.pie(names=labels, values=values)

# Linear Regression
What factors play into the annual mean wage of CNAS? 
y will be the annual mean wage for the cnas, aka a_mean

Simple regression: y = a_mean x = total_emp

In [64]:
import statsmodels.api as sm
x = df_cna_by_state_job_stats['jobs_1000']
x = sm.add_constant(x)
y = df_cna_by_state_job_stats['a_mean']
simple_regression_model = sm.OLS(y,x).fit()
print(simple_regression_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 a_mean   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                 -0.015
Method:                 Least Squares   F-statistic:                    0.2260
Date:                Wed, 19 Aug 2026   Prob (F-statistic):              0.636
Time:                        16:55:55   Log-Likelihood:                -537.09
No. Observations:                  54   AIC:                             1078.
Df Residuals:                      52   BIC:                             1082.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.167e+04   2056.410     20.264      0.000    3.75e+04    4.58e+04
jobs_1000    -95.1246    200.084     -0.475      0.636    -496.623     306.374
==============================================================================
Omnibus:                        4.549   Durbin-Watson:                   2.106
Prob(Omnibus):                  0.103   Jarque-Bera (JB):                3.476
Skew:                          -0.541   Prob(JB):                        0.176
Kurtosis:                       3.613   Cond. No.                         30.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [65]:
mutliple_x = df_cna_by_state_job_stats[['jobs_1000', 'tot_emp','loc_quotient']]
mutliple_x= sm.add_constant(mutliple_x)
y = df_cna_by_state_job_stats['a_mean']

multiple_regression_model = sm.OLS(y,mutliple_x).fit()
print(multiple_regression_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 a_mean   R-squared:                       0.022
Model:                            OLS   Adj. R-squared:                 -0.037
Method:                 Least Squares   F-statistic:                    0.3717
Date:                Wed, 19 Aug 2026   Prob (F-statistic):              0.774
Time:                        16:55:55   Log-Likelihood:                -536.61
No. Observations:                  54   AIC:                             1081.
Df Residuals:                      50   BIC:                             1089.
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         4.133e+04   2216.377     18.647      0.000    3.69e+04    4.58e+04
jobs_1000     -1.74e+04   3.05e+04     -0.571      0.570   -7.86e+04    4.38e+04
tot_emp          0.0210      0.028      0.739      0.463      -0.036       0.078
loc_quotient  1.557e+05   2.74e+05      0.568      0.573   -3.95e+05    7.07e+05
==============================================================================
Omnibus:                        3.475   Durbin-Watson:                   2.147
Prob(Omnibus):                  0.176   Jarque-Bera (JB):                2.491
Skew:                          -0.471   Prob(JB):                        0.288
Kurtosis:                       3.467   Cond. No.                     1.40e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

#tried teting to seee what affects the mean. tht didn't seem effective, so how about the other way around? are jobs_1000 higher in places with higher mean?
jobs_1000 will be the y, a_mean will bet he x
#NOTE: this doesnt seem effecetive either, the mean doesnt seem to effect the jobs_1000. the only thing that did was loc_quoteint, but there's an error with that becuase the correaltion for loc_quoteint and jobs_1000 was like 0.999 whcih is imposisble unless they are the same variable

do more employees mean less, or higher, pay?
simpel regressoin, x = TOT_EMP, y = A_MEAN