8-19-2026
looking to see which is the most common job per state

In [1]:
import plotly.express as px
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# #Loading csvs into postegree sql
# df_by_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/by_state_job_stats_bls.csv")
# engine= create_engine('postgresql+psycopg2://postgres:Jehovah1@localhost:5432/bls_jobs')
# df_by_job_stats.columns=[col.lower() for col in df_by_job_stats]
# df_by_job_stats.to_sql('by_state_job_stats', engine, if_exists='replace', index=False)

# #national one
# df_national_jobs_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/national_job_stats_bls.csv")
# engine= create_engine('postgresql+psycopg2://postgres:Jehovah1@localhost:5432/bls_jobs')
# df_national_jobs_stats.columns=[col.lower() for col in df_national_jobs_stats]
# df_national_jobs_stats.to_sql('national_job_stats', engine, if_exists='replace', index=False)

In [3]:
df_by_state_job_stats = pd.read_csv("/Users/Kayin/Github/My_python_projects_github/Jobs Analysis 1/by_state_job_stats_bls_lowercase.csv")

In [4]:
df_by_state_job_stats

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90,annual,hourly
0,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,21.07,30.82,47.51,"23,520","30,660","43,830","64,110","98,810",NaN,NaN
1,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,48.39,68.50,98.03,"51,100","72,870","100,640","142,480","203,900",NaN,NaN
2,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,79.04,106.69,#,"104,950","130,950","164,400","221,910",#,NaN,NaN
3,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,51.12,78.26,#,"50,410","74,720","106,330","162,780",#,NaN,NaN
4,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1031,Legislators,...,*,*,*,"18,270","20,950","26,990","41,760","63,900",True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37604,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7051,Industrial Truck and Tractor Operators,...,15.36,17.00,18.91,"30,710","31,950","31,950","35,360","39,330",NaN,NaN
37605,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7061,Cleaners of Vehicles and Equipment,...,13.12,14.63,18.81,"21,840","24,960","27,290","30,430","39,120",NaN,NaN
37606,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7062,"Laborers and Freight, Stock, and Material Move...",...,15.81,17.66,18.71,"27,970","29,120","32,890","36,740","38,910",NaN,NaN
37607,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,11.98,14.93,17.99,"22,380","22,750","24,920","31,060","37,410",NaN,NaN
37608,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,13.85,14.27,16.93,"23,040","24,480","28,800","29,680","35,210",NaN,NaN

In [5]:
df_by_state_job_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37609 entries, 0 to 37608
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area          37609 non-null  int64
 1   area_title    37609 non-null  object
 2   area_type     37609 non-null  int64
 3   prim_state    37609 non-null  object
 4   naics         37609 non-null  int64
 5   naics_title   37609 non-null  object
 6   i_group       37609 non-null  object
 7   own_code      37609 non-null  int64
 8   occ_code      37609 non-null  object
 9   occ_title     37609 non-null  object
 10  o_group       37609 non-null  object
 11  tot_emp       37609 non-null  object
 12  emp_prse      37609 non-null  object
 13  jobs_1000     37609 non-null  object
 14  loc_quotient  37609 non-null  object
 15  pct_total     0 non-null      float64
 16  pct_rpt       0 non-null      float64
 17  h_mean        37609 non-null  object
 18  a_mean        37609 non-null  object
 19  mean_prse     37609 non-null  object
 20  h_pct10       37609 non-null  object
 21  h_pct25       37609 non-null  object
 22  h_median      37609 non-null  object
 23  h_pct75       37609 non-null  object
 24  h_pct90       37609 non-null  object
 25  a_pct10       37609 non-null  object
 26  a_pct25       37609 non-null  object
 27  a_median      37609 non-null  object
 28  a_pct75       37609 non-null  object
 29  a_pct90       37609 non-null  object
 30  annual        2666 non-null   object
 31  hourly        162 non-null    object
dtypes: float64(2), int64(4), object(26)
memory usage: 9.2+ MB

In [6]:
#4 columns have only null vlaues so ill drop them 
df_by_state_job_stats.drop(['pct_total','pct_rpt','hourly', 'annual'], axis=1, inplace=True)
df_by_state_job_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37609 entries, 0 to 37608
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area          37609 non-null  int64
 1   area_title    37609 non-null  object
 2   area_type     37609 non-null  int64
 3   prim_state    37609 non-null  object
 4   naics         37609 non-null  int64
 5   naics_title   37609 non-null  object
 6   i_group       37609 non-null  object
 7   own_code      37609 non-null  int64
 8   occ_code      37609 non-null  object
 9   occ_title     37609 non-null  object
 10  o_group       37609 non-null  object
 11  tot_emp       37609 non-null  object
 12  emp_prse      37609 non-null  object
 13  jobs_1000     37609 non-null  object
 14  loc_quotient  37609 non-null  object
 15  h_mean        37609 non-null  object
 16  a_mean        37609 non-null  object
 17  mean_prse     37609 non-null  object
 18  h_pct10       37609 non-null  object
 19  h_pct25       37609 non-null  object
 20  h_median      37609 non-null  object
 21  h_pct75       37609 non-null  object
 22  h_pct90       37609 non-null  object
 23  a_pct10       37609 non-null  object
 24  a_pct25       37609 non-null  object
 25  a_median      37609 non-null  object
 26  a_pct75       37609 non-null  object
 27  a_pct90       37609 non-null  object
dtypes: int64(4), object(24)
memory usage: 8.0+ MB

In [ ]:
#in order to get the highest number of employmen, we need ot remove the all occcupations row from each state. that row shows total employment for the whole state which is not what we want 
df_by_state_job_stats = df_by_state_job_stats[df_by_state_job_stats['jobs_1000'] != '1000.000']

In [8]:
df_by_state_job_stats

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_pct10,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90
1,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,24.57,35.03,48.39,68.50,98.03,"51,100","72,870","100,640","142,480","203,900"
2,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,50.46,62.96,79.04,106.69,#,"104,950","130,950","164,400","221,910",#
3,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,24.24,35.92,51.12,78.26,#,"50,410","74,720","106,330","162,780",#
4,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1031,Legislators,...,*,*,*,*,*,"18,270","20,950","26,990","41,760","63,900"
5,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-2011,Advertising and Promotions Managers,...,40.18,41.59,64.22,69.57,72.44,"83,570","86,500","133,570","144,710","150,670"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37604,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7051,Industrial Truck and Tractor Operators,...,14.77,15.36,15.36,17.00,18.91,"30,710","31,950","31,950","35,360","39,330"
37605,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7061,Cleaners of Vehicles and Equipment,...,10.50,12.00,13.12,14.63,18.81,"21,840","24,960","27,290","30,430","39,120"
37606,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7062,"Laborers and Freight, Stock, and Material Move...",...,13.45,14.00,15.81,17.66,18.71,"27,970","29,120","32,890","36,740","38,910"
37607,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,10.76,10.94,11.98,14.93,17.99,"22,380","22,750","24,920","31,060","37,410"
37608,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,11.08,11.77,13.85,14.27,16.93,"23,040","24,480","28,800","29,680","35,210"

In [9]:
df_by_state_job_stats['tot_emp'] = pd.to_numeric(df_by_state_job_stats['tot_emp'].str.replace(',', ''), errors='coerce')
df_by_state_job_stats['tot_emp']

/var/folders/9r/0wy81gln1bv565v23phr081h0000gn/T/ipykernel_33956/3316650564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_by_state_job_stats['tot_emp'] = pd.to_numeric(df_by_state_job_stats['tot_emp'].str.replace(',', ''), errors='coerce')

1        110240.0
2           830.0
3         32370.0
4          1120.0
5            50.0
           ...
37604        40.0
37605        50.0
37606       480.0
37607       120.0
37608       440.0
Name: tot_emp, Length: 37555, dtype: float64

In [17]:
df_by_state_job_stats_most_emp = df_by_state_job_stats.sort_values(by='tot_emp',ascending=False)

In [ ]:
df_by_state_job_stats_most_emp.head() #most common jobs in the US

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_pct10,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90
3248,6,California,2,CA,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,18.03,21.04,25.05,31.50,39.09,"37,510","43,750","52,100","65,520","81,310"
31388,48,Texas,2,TX,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,13.77,16.96,20.99,26.44,34.50,"28,630","35,280","43,650","54,990","71,760"
3164,6,California,2,CA,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,16.40,17.00,18.05,21.60,26.35,"34,110","35,360","37,540","44,920","54,820"
3529,6,California,2,CA,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,17.00,18.11,21.78,27.59,34.79,"35,370","37,670","45,300","57,390","72,360"
3225,6,California,2,CA,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,16.61,17.39,21.21,30.77,50.75,"34,550","36,180","44,120","64,010","105,570"

In [49]:
#picking the top highest job type from each state
# the problem i ran into this was every state's most employed job fell in to the same category- office! 
#so i changed it to be the top 2 highest job types
# this is done by grouping them by their state name then keeping first 2
df_top_2_highest_emp_by_state = df_by_state_job_stats_most_emp.groupby('area_title').head(2)
# df_highest_emp_by_state = df_by_state_job_stats_most_emp.drop_duplicates(subset= ['area_title'], keep='first, second')

In [50]:
df_top_2_highest_emp_by_state.head()

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_pct10,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90
3248,6,California,2,CA,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,18.03,21.04,25.05,31.50,39.09,"37,510","43,750","52,100","65,520","81,310"
31388,48,Texas,2,TX,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,13.77,16.96,20.99,26.44,34.50,"28,630","35,280","43,650","54,990","71,760"
3164,6,California,2,CA,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,16.40,17.00,18.05,21.60,26.35,"34,110","35,360","37,540","44,920","54,820"
6641,12,Florida,2,FL,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,14.97,17.48,21.00,25.66,32.89,"31,150","36,360","43,680","53,370","68,400"
31306,48,Texas,2,TX,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,9.22,10.92,13.67,17.21,21.60,"19,170","22,710","28,440","35,790","44,930"

In [51]:
#b below is jsut to make sure that every state is included so i put them in order by the state name
# df_top_2_highest_emp_by_state.sort_values(by='area_title', inplace=True)

In [52]:
df_top_2_highest_emp_by_state

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_pct10,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90
3248,6,California,2,CA,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,18.03,21.04,25.05,31.50,39.09,"37,510","43,750","52,100","65,520","81,310"
31388,48,Texas,2,TX,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,13.77,16.96,20.99,26.44,34.50,"28,630","35,280","43,650","54,990","71,760"
3164,6,California,2,CA,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,16.40,17.00,18.05,21.60,26.35,"34,110","35,360","37,540","44,920","54,820"
6641,12,Florida,2,FL,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,14.97,17.48,21.00,25.66,32.89,"31,150","36,360","43,680","53,370","68,400"
31306,48,Texas,2,TX,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,9.22,10.92,13.67,17.21,21.60,"19,170","22,710","28,440","35,790","44,930"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36451,56,Wyoming,2,WY,0,Cross-industry,cross-industry,1235,47-0000,Construction and Extraction Occupations,...,18.85,22.72,27.95,36.62,42.11,"39,210","47,250","58,130","76,160","87,600"
36743,66,Guam,3,GU,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,10.72,12.13,15.37,20.74,27.07,"22,290","25,230","31,960","43,140","56,300"
36699,66,Guam,3,GU,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,9.61,9.79,10.56,10.98,13.51,"19,990","20,370","21,960","22,830","28,110"
37539,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,13.45,15.34,19.23,24.58,30.39,"27,980","31,900","39,990","51,130","63,200"
37499,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,11.08,11.77,14.34,20.87,31.95,"23,050","24,480","29,820","43,410","66,450"

In [53]:
# then i decided to only keep the secon dhighest job, since the first is the smae for every state anywya:

df_second_highest_emp_by_state = df_top_2_highest_emp_by_state.drop_duplicates(subset= ['area_title'], keep='last')

In [54]:
df_second_highest_emp_by_state

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_pct10,h_pct25,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90
3164,6,California,2,CA,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,16.40,17.00,18.05,21.60,26.35,"34,110","35,360","37,540","44,920","54,820"
31306,48,Texas,2,TX,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,9.22,10.92,13.67,17.21,21.60,"19,170","22,710","28,440","35,790","44,930"
6619,12,Florida,2,FL,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,13.17,14.25,17.68,27.83,44.82,"27,380","29,640","36,770","57,890","93,220"
23228,36,New York,2,NY,0,Cross-industry,cross-industry,1235,31-0000,Healthcare Support Occupations,...,16.96,17.73,18.59,21.67,24.26,"35,280","36,880","38,670","45,070","50,460"
9725,17,Illinois,2,IL,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,15.04,17.41,21.12,26.73,35.89,"31,270","36,220","43,930","55,590","74,650"
28129,42,Pennsylvania,2,PA,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,13.68,17.08,20.87,25.75,31.27,"28,460","35,520","43,400","53,550","65,040"
25814,39,Ohio,2,OH,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.19,17.08,19.67,24.56,31.92,"29,520","35,520","40,910","51,090","66,400"
7701,13,Georgia,2,GA,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,13.82,16.46,19.30,24.67,34.32,"28,750","34,240","40,150","51,320","71,390"
24127,37,North Carolina,2,NC,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,11.15,13.51,17.29,28.28,47.19,"23,190","28,100","35,950","58,810","98,160"
22151,34,New Jersey,2,NJ,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,15.31,17.35,20.92,26.98,35.77,"31,840","36,090","43,520","56,120","74,400"
16340,26,Michigan,2,MI,0,Cross-industry,cross-industry,1235,51-0000,Production Occupations,...,16.63,17.98,21.86,28.15,36.03,"34,590","37,390","45,470","58,560","74,950"
33076,51,Virginia,2,VA,0,Cross-industry,cross-industry,1235,13-0000,Business and Financial Operations Occupations,...,24.06,31.44,44.26,60.59,78.55,"50,030","65,400","92,050","126,020","163,390"
30843,47,Tennessee,2,TN,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.25,16.90,19.05,23.68,33.49,"29,630","35,150","39,630","49,260","69,660"
10516,18,Indiana,2,IN,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.56,17.19,20.76,25.50,33.17,"30,290","35,750","43,190","53,050","68,990"
14926,25,Massachusetts,2,MA,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,34.25,47.88,70.40,101.49,#,"71,240","99,600","146,440","211,090",#
35928,55,Wisconsin,2,WI,0,Cross-industry,cross-industry,1235,51-0000,Production Occupations,...,17.29,19.20,23.10,28.12,32.93,"35,950","39,940","48,040","58,490","68,500"
4033,8,Colorado,2,CO,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,15.39,17.44,22.31,36.33,59.34,"32,000","36,280","46,400","75,570","123,420"
34301,53,Washington,2,WA,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,16.96,18.01,22.49,34.11,50.00,"35,270","37,450","46,770","70,950","103,990"
1749,4,Arizona,2,AZ,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,14.57,15.95,18.04,27.90,44.38,"30,310","33,180","37,520","58,040","92,310"
18342,29,Missouri,2,MO,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,12.30,13.14,14.34,17.20,20.93,"25,580","27,340","29,820","35,770","43,530"
14160,24,Maryland,2,MD,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,29.83,41.74,62.02,83.39,108.99,"62,050","86,820","129,000","173,450","226,700"
16935,27,Minnesota,2,MN,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,13.82,16.03,18.46,29.99,47.80,"28,750","33,340","38,410","62,380","99,420"
29198,45,South Carolina,2,SC,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,10.68,13.17,16.50,24.57,42.46,"22,210","27,400","34,310","51,100","88,310"
12729,21,Kentucky,2,KY,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.12,16.89,20.51,24.54,32.02,"29,370","35,120","42,660","51,050","66,610"
602,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,51-0000,Production Occupations,...,13.50,16.36,19.92,25.15,33.05,"28,080","34,030","41,440","52,300","68,740"
13146,22,Louisiana,2,LA,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,7.30,9.42,11.33,14.80,18.56,"15,180","19,590","23,570","30,780","38,610"
20494,32,Nevada,2,NV,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,14.85,17.76,21.36,25.82,31.95,"30,880","36,940","44,430","53,710","66,450"
26992,41,Oregon,2,OR,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,14.59,15.66,17.12,20.74,24.81,"30,350","32,560","35,600","43,140","51,600"
26234,40,Oklahoma,2,OK,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,8.58,10.48,12.83,15.15,19.35,"17,850","21,790","26,690","31,510","40,250"
4347,9,Connecticut,2,CT,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,33.03,47.54,65.74,89.07,#,"68,700","98,890","136,750","185,270",#
11267,19,Iowa,2,IA,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.33,17.64,21.83,26.09,32.93,"29,800","36,700","45,410","54,270","68,490"
32160,49,Utah,2,UT,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,13.19,14.68,18.14,28.68,43.26,"27,440","30,540","37,720","59,640","89,990"
2711,5,Arkansas,2,AR,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,13.50,14.99,18.12,23.34,32.70,"28,080","31,180","37,680","48,540","68,010"
11981,20,Kansas,2,KS,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.25,17.18,20.89,24.88,32.75,"29,650","35,720","43,450","51,760","68,120"
17904,28,Mississippi,2,MS,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,12.30,14.92,18.23,23.24,30.77,"25,580","31,030","37,910","48,330","64,010"
37187,72,Puerto Rico,3,PR,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,9.50,9.80,10.48,13.61,18.13,"19,760","20,380","21,800","28,320","37,710"
5629,11,District of Columbia,2,DC,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,44.51,62.38,80.42,94.59,#,"92,580","129,750","167,270","196,740",#
20014,31,Nebraska,2,NE,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,14.37,17.40,20.53,25.66,36.25,"29,890","36,200","42,700","53,380","75,400"
22548,35,New Mexico,2,NM,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,12.74,13.36,14.36,17.29,22.15,"26,490","27,790","29,860","35,960","46,080"
8124,15,Hawaii,2,HI,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,...,16.26,18.73,23.10,29.12,35.64,"33,820","38,950","48,060","60,580","74,120"
8674,16,Idaho,2,ID,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,9.02,11.12,14.21,17.41,21.63,"18,760","23,120","29,560","36,210","44,990"
21151,33,New Hampshire,2,NH,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,13.62,15.12,17.95,28.87,47.67,"28,330","31,450","37,340","60,040","99,160"
34869,54,West Virginia,2,WV,0,Cross-industry,cross-industry,1235,29-0000,Healthcare Practitioners and Technical Occupat...,...,17.71,23.86,33.34,46.86,68.10,"36,850","49,620","69,340","97,460","141,650"
13894,23,Maine,2,ME,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,14.66,16.35,18.07,25.34,36.53,"30,500","34,000","37,580","52,720","75,980"
19060,30,Montana,2,MT,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,10.46,11.27,14.40,17.62,22.13,"21,750","23,450","29,960","36,650","46,020"
28490,44,Rhode Island,2,RI,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,14.00,14.50,16.94,22.26,28.42,"29,120","30,160","35,240","46,290","59,110"
5364,10,Delaware,2,DE,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,13.25,13.95,16.44,18.97,23.90,"27,560","29,010","34,200","39,460","49,720"
29868,46,South Dakota,2,SD,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,13.36,14.22,17.66,29.02,44.79,"27,790","29,580","36,730","60,370","93,170"
25019,38,North Dakota,2,ND,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,15.69,18.56,22.98,29.12,37.70,"32,630","38,610","47,800","60,560","78,420"
1267,2,Alaska,2,AK,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,...,16.99,18.75,24.71,37.21,56.87,"35,350","39,010","51,390","77,390","118,290"
32817,50,Vermont,2,VT,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,...,14.68,16.74,19.19,28.31,47.34,"30,530","34,830","39,910","58,890","98,470"
36451,56,Wyoming,2,WY,0,Cross-industry,cross-industry,1235,47-0000,Construction and Extraction Occupations,...,18.85,22.72,27.95,36.62,42.11,"39,210","47,250","58,130","76,160","87,600"
36699,66,Guam,3,GU,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,9.61,9.79,10.56,10.98,13.51,"19,990","20,370","21,960","22,830","28,110"
37499,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,...,11.08,11.77,14.34,20.87,31.95,"23,050","24,480","29,820","43,410","66,450"

In [55]:
# putting in order bystate name 
df_second_highest_emp_by_state.sort_values(by='area_title', inplace=True)

/var/folders/9r/0wy81gln1bv565v23phr081h0000gn/T/ipykernel_33956/605692754.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_second_highest_emp_by_state.sort_values(by='area_title', inplace=True)

In [ ]:
df_second_highest_emp_by_state

In [57]:
# turnign the df to a csv so i can map it and export it 
df_second_highest_emp_by_state.to_csv("Second most common job types for each state", index=False)